import { UserRole, RoleConfig, SessionUser } from "@/types/auth";

export const ROLE_CONFIGS: Record<UserRole, RoleConfig> = {
  SUPER_ADMIN: {
    role: "SUPER_ADMIN",
    displayName: "Super Admin",
    description: "Platform-wide system configuration, tenant management, and root telemetry",
    badgeColor: "bg-rose-primary text-white",
    dashboardPath: "/admin",
    allowedNav: ["admin", "institution", "students", "faculty", "lms", "attendance", "timetable", "assignments", "examinations", "finance", "library", "research", "careers", "scholarships", "communication", "analytics", "ai-assistant", "documents"],
  },
  INSTITUTION_ADMIN: {
    role: "INSTITUTION_ADMIN",
    displayName: "Institution Admin",
    description: "Campus operations, department governance, and academic administration",
    badgeColor: "bg-rose-primary text-white",
    dashboardPath: "/institution",
    allowedNav: ["institution", "students", "faculty", "lms", "attendance", "timetable", "examinations", "finance", "library", "communication", "analytics", "ai-assistant", "documents"],
  },
  PRINCIPAL: {
    role: "PRINCIPAL",
    displayName: "Principal / Director",
    description: "Executive oversight, accreditation evidence, and faculty governance",
    badgeColor: "bg-rose-accent text-white",
    dashboardPath: "/analytics",
    allowedNav: ["analytics", "institution", "students", "faculty", "attendance", "examinations", "research", "communication", "ai-assistant"],
  },
  HOD: {
    role: "HOD",
    displayName: "Head of Department",
    description: "Department course scheduling, faculty workload, and cohort monitoring",
    badgeColor: "bg-rose-accent text-white",
    dashboardPath: "/institution",
    allowedNav: ["institution", "faculty", "students", "timetable", "attendance", "examinations", "research", "ai-assistant"],
  },
  FACULTY: {
    role: "FACULTY",
    displayName: "Faculty / Professor",
    description: "Course delivery, attendance taking, assignment grading, and research",
    badgeColor: "bg-academic-info text-white",
    dashboardPath: "/faculty",
    allowedNav: ["faculty", "attendance", "lms", "assignments", "timetable", "examinations", "research", "ai-assistant", "communication"],
  },
  CLASS_TEACHER: {
    role: "CLASS_TEACHER",
    displayName: "Class Teacher",
    description: "Section mentoring, daily attendance audits, and parent coordination",
    badgeColor: "bg-academic-info text-white",
    dashboardPath: "/students",
    allowedNav: ["students", "attendance", "timetable", "communication", "ai-assistant"],
  },
  STUDENT: {
    role: "STUDENT",
    displayName: "Student",
    description: "Enrolled courses, assignments, exams, grades, attendance, and career hub",
    badgeColor: "bg-academic-success text-white",
    dashboardPath: "/students/profile",
    allowedNav: ["students/profile", "lms", "attendance", "timetable", "assignments", "examinations", "finance", "library", "careers", "scholarships", "ai-assistant", "documents"],
  },
  PARENT: {
    role: "PARENT",
    displayName: "Parent / Guardian",
    description: "Child attendance, grades, fee installments, and teacher communication",
    badgeColor: "bg-academic-warning text-white",
    dashboardPath: "/parent",
    allowedNav: ["parent", "communication", "ai-assistant"],
  },
  ACCOUNTANT: {
    role: "ACCOUNTANT",
    displayName: "Accountant",
    description: "Tuition structures, fee receipts, payment reconciliation, and refunds",
    badgeColor: "bg-academic-warning text-white",
    dashboardPath: "/finance",
    allowedNav: ["finance", "scholarships", "analytics", "documents"],
  },
  LIBRARIAN: {
    role: "LIBRARIAN",
    displayName: "Librarian",
    description: "Book cataloging, ISBN loans, fine tracking, and digital archives",
    badgeColor: "bg-rose-accent text-white",
    dashboardPath: "/library",
    allowedNav: ["library", "students", "analytics"],
  },
  EXAMINATION_CONTROLLER: {
    role: "EXAMINATION_CONTROLLER",
    displayName: "Exam Controller",
    description: "Question paper banking, exam schedules, grading curves, and GPA transcripts",
    badgeColor: "bg-rose-primary text-white",
    dashboardPath: "/examinations",
    allowedNav: ["examinations", "courses", "analytics", "documents"],
  },
  PLACEMENT_OFFICER: {
    role: "PLACEMENT_OFFICER",
    displayName: "Placement Officer",
    description: "Corporate recruitment drives, internship postings, and mock interview drills",
    badgeColor: "bg-academic-info text-white",
    dashboardPath: "/careers",
    allowedNav: ["careers", "students", "analytics"],
  },
  RESEARCH_COORDINATOR: {
    role: "RESEARCH_COORDINATOR",
    displayName: "Research Coordinator",
    description: "Funded research projects, peer-reviewed publications, and patents",
    badgeColor: "bg-rose-accent text-white",
    dashboardPath: "/research",
    allowedNav: ["research", "faculty", "analytics"],
  },
  HR_STAFF: {
    role: "HR_STAFF",
    displayName: "HR & Staff Manager",
    description: "Faculty leave management, service records, and personnel appraisals",
    badgeColor: "bg-charcoal-800 text-white",
    dashboardPath: "/faculty",
    allowedNav: ["faculty", "communication", "documents"],
  },
  ALUMNI: {
    role: "ALUMNI",
    displayName: "Alumni Member",
    description: "Alumni network, career mentorship, events, and transcripts",
    badgeColor: "bg-academic-info text-white",
    dashboardPath: "/careers",
    allowedNav: ["careers", "communication"],
  },
  GUEST: {
    role: "GUEST",
    displayName: "Guest / Auditor",
    description: "Read-only inspection of campus facilities and public course offerings",
    badgeColor: "bg-charcoal-600 text-white",
    dashboardPath: "/institution",
    allowedNav: ["institution", "library"],
  },
};

// Default Realistic Personas for Instant Interactive Demo & Testing
export const MOCK_USERS: Record<UserRole, SessionUser> = {
  SUPER_ADMIN: {
    id: "usr-admin-01",
    email: "provost.evans@classroom.edu",
    firstName: "Elena",
    lastName: "Evans",
    fullName: "Provost Elena Evans",
    role: "SUPER_ADMIN",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
    campusId: "cmp-main-01",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
  INSTITUTION_ADMIN: {
    id: "usr-instadmin-01",
    email: "admin@apex.edu",
    firstName: "Marcus",
    lastName: "Vance",
    fullName: "Registrar Marcus Vance",
    role: "INSTITUTION_ADMIN",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
    campusId: "cmp-main-01",
  },
  PRINCIPAL: {
    id: "usr-principal-01",
    email: "director@apex.edu",
    firstName: "Arthur",
    lastName: "Pendleton",
    fullName: "Director Arthur Pendleton",
    role: "PRINCIPAL",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
  },
  HOD: {
    id: "usr-hod-01",
    email: "hod.cs@apex.edu",
    firstName: "Radhika",
    lastName: "Gupta",
    fullName: "Dr. Radhika Gupta (HOD Computer Science)",
    role: "HOD",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
    departmentId: "dept-cs-01",
  },
  FACULTY: {
    id: "usr-fac-01",
    email: "sarah.chen@apex.edu",
    firstName: "Sarah",
    lastName: "Chen",
    fullName: "Prof. Sarah Chen",
    role: "FACULTY",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
    departmentId: "dept-cs-01",
    facultyId: "fac-chen-01",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  CLASS_TEACHER: {
    id: "usr-teacher-01",
    email: "david.miller@apex.edu",
    firstName: "David",
    lastName: "Miller",
    fullName: "Prof. David Miller (Section A Advisor)",
    role: "CLASS_TEACHER",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
  },
  STUDENT: {
    id: "usr-stu-01",
    email: "alex.mercer@apex.edu",
    firstName: "Alex",
    lastName: "Mercer",
    fullName: "Alex Mercer",
    role: "STUDENT",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
    studentId: "stu-mercer-01",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
  },
  PARENT: {
    id: "usr-parent-01",
    email: "katherine.mercer@gmail.com",
    firstName: "Katherine",
    lastName: "Mercer",
    fullName: "Katherine Mercer (Alex's Mother)",
    role: "PARENT",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
    parentId: "par-mercer-01",
  },
  ACCOUNTANT: {
    id: "usr-acc-01",
    email: "bursar@apex.edu",
    firstName: "Robert",
    lastName: "Sterling",
    fullName: "Robert Sterling (Chief Bursar)",
    role: "ACCOUNTANT",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
  },
  LIBRARIAN: {
    id: "usr-lib-01",
    email: "library@apex.edu",
    firstName: "Eleanor",
    lastName: "Vane",
    fullName: "Eleanor Vane (Head Librarian)",
    role: "LIBRARIAN",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
  },
  EXAMINATION_CONTROLLER: {
    id: "usr-coe-01",
    email: "coe@apex.edu",
    firstName: "Vikram",
    lastName: "Sarin",
    fullName: "Dr. Vikram Sarin (Controller of Exams)",
    role: "EXAMINATION_CONTROLLER",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
  },
  PLACEMENT_OFFICER: {
    id: "usr-place-01",
    email: "careers@apex.edu",
    firstName: "Jessica",
    lastName: "Alvarez",
    fullName: "Jessica Alvarez (Head of Corporate Relations)",
    role: "PLACEMENT_OFFICER",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
  },
  RESEARCH_COORDINATOR: {
    id: "usr-res-01",
    email: "research@apex.edu",
    firstName: "Alan",
    lastName: "Kowalski",
    fullName: "Dr. Alan Kowalski (Dean of Research)",
    role: "RESEARCH_COORDINATOR",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
  },
  HR_STAFF: {
    id: "usr-hr-01",
    email: "hr@apex.edu",
    firstName: "Samantha",
    lastName: "Brooks",
    fullName: "Samantha Brooks (HR Officer)",
    role: "HR_STAFF",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
  },
  ALUMNI: {
    id: "usr-alumni-01",
    email: "tariq.alumni@techcorp.io",
    firstName: "Tariq",
    lastName: "Mansoor",
    fullName: "Tariq Mansoor (Class of '22 • Staff Engineer at DeepAI)",
    role: "ALUMNI",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
  },
  GUEST: {
    id: "usr-guest-01",
    email: "guest@accreditation-board.org",
    firstName: "Accreditation",
    lastName: "Auditor",
    fullName: "ABET / NAAC Accreditation Visitor",
    role: "GUEST",
    institutionId: "inst-apex-01",
    institutionName: "Apex University of Science & Technology",
  },
};
