version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classroom-erp-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://classroom_user:classroom_secure_pass_2026@postgres:5432/classroom_erp?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - AUTH_SECRET=production_classroom_erp_jwt_secret_token_2026
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    container_name: classroom-erp-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=classroom_user
      - POSTGRES_PASSWORD=classroom_secure_pass_2026
      - POSTGRES_DB=classroom_erp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U classroom_user -d classroom_erp"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: classroom-erp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
