export interface RawBiologyCourse {
  code: string;
  title: string;
  shortName: string;
  description: string;
  subjectType: "CORE" | "LAB" | "PROGRAM_ELECTIVE" | "OPEN_ELECTIVE" | "ABILITY_ENHANCEMENT" | "VALUE_ADDED" | "PROJECT";
  courseType: "THEORY" | "PRACTICAL";
  credits: number;
  lectureHours: number;
  tutorialHours: number;
  labHours: number;
  internalMarks: number;
  externalMarks: number;
  isElective: boolean;
  facultyId: "fac-raman-02" | "fac-sharma-05";
}

export const BIOLOGY_COURSES: RawBiologyCourse[] = [
  // Tier 1: Foundational Biology
  {
    code: "BIO-101",
    title: "General Biology & Principles of Life",
    shortName: "General Biology",
    description: "Fundamental concepts of biological systems, unity and diversity of life, cellular basis of heredity, and evolutionary mechanisms.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-101L",
    title: "General Biology & Optical Microscopy Lab",
    shortName: "General Bio Lab",
    description: "Microscopic analysis of eukaryotic and prokaryotic cells, vital staining, mitosis observation, and specimen preparation.",
    subjectType: "LAB",
    courseType: "PRACTICAL",
    credits: 2,
    lectureHours: 0,
    tutorialHours: 0,
    labHours: 4,
    internalMarks: 50,
    externalMarks: 50,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-102",
    title: "Evolutionary Biology & Population Ecology",
    shortName: "Evolution & Ecology",
    description: "Darwinian selection, modern synthesis, speciation modes, Hardy-Weinberg equilibrium, phylogenetic tree modeling, and adaptive radiation.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-103",
    title: "Botany: Plant Anatomy, Taxonomy & Physiology",
    shortName: "Plant Biology",
    description: "Angiosperm and gymnosperm morphology, plant tissue systems, photosynthetic light and dark reactions (C3/C4/CAM), and phytohormone signaling.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-103L",
    title: "Plant Physiology & Botanical Specimen Lab",
    shortName: "Botany Lab",
    description: "Stomatal index determination, paper chromatography of photosynthetic pigments, transpiration measurement, and plant anatomical sectioning.",
    subjectType: "LAB",
    courseType: "PRACTICAL",
    credits: 2,
    lectureHours: 0,
    tutorialHours: 0,
    labHours: 4,
    internalMarks: 50,
    externalMarks: 50,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-104",
    title: "Zoology: Animal Diversity, Physiology & Histology",
    shortName: "Animal Biology",
    description: "Invertebrate and vertebrate taxonomy, comparative organ systems, homeostatic mechanisms, and mammalian tissue histology.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-104L",
    title: "Comparative Animal Anatomy & Dissection Lab",
    shortName: "Zoology Lab",
    description: "Histological slide examination, dissection of representative animal organ models, blood smear staining, and hemolymph observation.",
    subjectType: "LAB",
    courseType: "PRACTICAL",
    credits: 2,
    lectureHours: 0,
    tutorialHours: 0,
    labHours: 4,
    internalMarks: 50,
    externalMarks: 50,
    isElective: false,
    facultyId: "fac-raman-02",
  },

  // Tier 2: Cellular, Molecular & Genetics
  {
    code: "BIO-201",
    title: "Cell Biology & Cytoskeleton Dynamics",
    shortName: "Cell Biology",
    description: "Membrane transport mechanisms, nuclear pore complex, protein targeting to ER and Golgi, actin-myosin cytoskeleton, and apoptosis pathways.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-201L",
    title: "Cell Biology & Fluorescence Microscopy Lab",
    shortName: "Cell Bio Lab",
    description: "Cell fractionation by differential centrifugation, organelle marker assays, cell viability assays (Trypan Blue/MTT), and fluorescence imaging.",
    subjectType: "LAB",
    courseType: "PRACTICAL",
    credits: 2,
    lectureHours: 0,
    tutorialHours: 0,
    labHours: 4,
    internalMarks: 50,
    externalMarks: 50,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-202",
    title: "Molecular Genetics & Chromosome Architecture",
    shortName: "Molecular Genetics",
    description: "Chromosome packaging, telomeres, nucleosome positioning, homologous recombination, DNA repair mechanisms, and linkage mapping.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-203",
    title: "Structural Biochemistry & Enzymology",
    shortName: "Biochemistry",
    description: "Protein quaternary folding, Michaelis-Menten enzyme kinetics, allosteric regulation, lineweaver-burk transformations, and lipid bilayers.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 2,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-203L",
    title: "Biochemical Analysis & Chromatography Lab",
    shortName: "Biochem Lab",
    description: "Protein quantitation by Bradford and Lowry assays, enzyme activity assays (amylase/catalase), and thin-layer chromatography (TLC).",
    subjectType: "LAB",
    courseType: "PRACTICAL",
    credits: 2,
    lectureHours: 0,
    tutorialHours: 0,
    labHours: 4,
    internalMarks: 50,
    externalMarks: 50,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-204",
    title: "Biophysics & Bioenergetics",
    shortName: "Biophysics",
    description: "Thermodynamics of biological reactions, Gibbs free energy in metabolic coupling, electrochemical proton gradients, and membrane action potentials.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-205",
    title: "Developmental Biology & Morphogenesis",
    shortName: "Dev Biology",
    description: "Embryonic cleavage patterns, gastrulation, neural tube formation, Homeobox (Hox) patterning genes, and cell fate specification.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-220",
    title: "Ecology & Biosphere Conservation",
    shortName: "Ecology",
    description: "Biogeochemical cycles (nitrogen, phosphorus, carbon), trophic cascade dynamics, niche partitioning, and ecosystem resilience under climate pressure.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-raman-02",
  },

  // Tier 3: Applied Biotechnology, Immunology & Health
  {
    code: "BIO-310",
    title: "Immunology & Serological Diagnostics",
    shortName: "Immunology",
    description: "Innate vs adaptive immunity, V(D)J genetic recombination, major histocompatibility complex (MHC I/II) presentation, and monoclonal antibodies.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-sharma-05",
  },
  {
    code: "BIO-310L",
    title: "Immunology, ELISA & Flow Cytometry Lab",
    shortName: "Immuno Lab",
    description: "Enzyme-linked immunosorbent assay (ELISA), agglutination tests, radial immunodiffusion, and leukocyte differential counting.",
    subjectType: "LAB",
    courseType: "PRACTICAL",
    credits: 2,
    lectureHours: 0,
    tutorialHours: 0,
    labHours: 4,
    internalMarks: 50,
    externalMarks: 50,
    isElective: false,
    facultyId: "fac-sharma-05",
  },
  {
    code: "BIO-320",
    title: "Plant Tissue Culture & Agrobacterium Transformation",
    shortName: "Plant Biotech",
    description: "Micropropagation protocols, callus induction, somatic embryogenesis, Agrobacterium tumefaciens binary vectors, and transgenic crop generation.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-325",
    title: "Marine Biology & Ocean Ecosystem Dynamics",
    shortName: "Marine Biology",
    description: "Pelagic and benthic marine communities, coral reef bleaching, deep-sea hydrothermal vent extremophiles, and marine biotechnology.",
    subjectType: "OPEN_ELECTIVE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-330",
    title: "Animal Cell Culture & Regenerative Stem Cell Biology",
    shortName: "Animal Biotech",
    description: "Primary cell isolation, immortalization, induced pluripotent stem cells (iPSCs), 3D organoid cultures, and cell therapy engineering.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-sharma-05",
  },
  {
    code: "BIO-340",
    title: "Bioprocess Engineering & Fermentation Technology",
    shortName: "Bioprocess Eng",
    description: "Stirred-tank bioreactor design, aeration and mass transfer (kLa), batch vs continuous culture kinetics, downstream cell disruption, and chromatography.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 2,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-sharma-05",
  },
  {
    code: "BIO-360",
    title: "Proteomics, Mass Spectrometry & Protein Engineering",
    shortName: "Proteomics",
    description: "MALDI-TOF and LC-MS/MS peptide mass fingerprinting, 2D gel electrophoresis, rational enzyme design, and directed evolution.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-370",
    title: "Human Anatomy & Systems Physiology",
    shortName: "Human Physiology",
    description: "Cardiovascular, pulmonary, renal, and gastrointestinal physiological regulation, autonomic nervous system, and acid-base blood buffer balance.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-370L",
    title: "Human Physiology & Electrocardiography Lab",
    shortName: "Physiology Lab",
    description: "Electrocardiogram (ECG) recording, spirometry lung volume measurements, blood pressure auscultation, and reflex arc testing.",
    subjectType: "LAB",
    courseType: "PRACTICAL",
    credits: 2,
    lectureHours: 0,
    tutorialHours: 0,
    labHours: 4,
    internalMarks: 50,
    externalMarks: 50,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-380",
    title: "Neurobiology, Synaptic Signaling & Brain Function",
    shortName: "Neurobiology",
    description: "Ion channel electrophysiology, patch clamping, neurotransmitter release kinetics, synaptic plasticity (LTP/LTD), and neurodegenerative pathologies.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-390",
    title: "Cancer Biology & Targeted Molecular Oncology",
    shortName: "Cancer Biology",
    description: "Hallmarks of cancer, oncogenes, tumor suppressor p53, receptor tyrosine kinase signaling (EGFR/HER2), metastasis cascade, and CAR-T immunotherapy.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-raman-02",
  },

  // Tier 4: Microbiology Specialty
  {
    code: "MIC-201",
    title: "General Microbiology & Microbial Taxonomy",
    shortName: "Microbiology",
    description: "Bacterial cell wall ultra-structure (Gram-positive/negative), archaea extremophiles, viral lytic/lysogenic cycles, and microbial growth mathematics.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 2,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-sharma-05",
  },
  {
    code: "MIC-201L",
    title: "Microbial Culturing & Gram Staining Laboratory",
    shortName: "Micro Lab",
    description: "Aseptic streak-plate technique, Gram staining, endospore staining, autoclave sterilization verification, and viable plate counting.",
    subjectType: "LAB",
    courseType: "PRACTICAL",
    credits: 2,
    lectureHours: 0,
    tutorialHours: 0,
    labHours: 4,
    internalMarks: 50,
    externalMarks: 50,
    isElective: false,
    facultyId: "fac-sharma-05",
  },
  {
    code: "MIC-301",
    title: "Medical Bacteriology & Antimicrobial Resistance",
    shortName: "Medical Bacteriology",
    description: "Pathogenic mechanisms of Staphylococcus, Mycobacterium tuberculosis, enterobacteria, and molecular mechanisms of beta-lactamase and carbapenemase resistance.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-sharma-05",
  },
  {
    code: "MIC-302",
    title: "Virology & Pathogen Host Interactions",
    shortName: "Virology",
    description: "Viral classification (Baltimore scheme), RNA/DNA replication strategies of SARS-CoV-2, HIV, Influenza, and host antiviral interferon responses.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-sharma-05",
  },
  {
    code: "MIC-303",
    title: "Medical Mycology & Parasitology",
    shortName: "Mycology & Parasitology",
    description: "Clinical pathology of Candida, Aspergillus, dermatophytes, protozoan life cycles (Plasmodium, Entamoeba), and anti-parasitic pharmacology.",
    subjectType: "CORE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: false,
    facultyId: "fac-sharma-05",
  },
  {
    code: "MIC-401",
    title: "Environmental Microbiology & Bioremediation",
    shortName: "Env Microbiology",
    description: "Microbial biodegradation of xenobiotic pollutants, hydrocarbon bioremediation, wastewater treatment bio-digesters, and bioleaching of metals.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-sharma-05",
  },
  {
    code: "MIC-402",
    title: "Food, Dairy & Agricultural Microbiology",
    shortName: "Food Microbiology",
    description: "Probiotic fermentation, foodborne pathogens (Salmonella, Listeria), Hazard Analysis Critical Control Points (HACCP), and Rhizobium biofertilizers.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-sharma-05",
  },

  // Tier 5: Modern Frontiers, CRISPR, Synthetic Genomes & Capstone
  {
    code: "BIO-425",
    title: "Conservation Genetics & Wildlife Forensics",
    shortName: "Wildlife Genetics",
    description: "Mitochondrial DNA barcoding for endangered species, microsatellite markers, inbreeding depression mitigation, and CITES anti-poaching tracking.",
    subjectType: "VALUE_ADDED",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-435",
    title: "Toxicology & Environmental Endocrine Disruptors",
    shortName: "Toxicology",
    description: "Dose-response curves (LD50/IC50), hepatic cytochrome P450 xenobiotic bio-transformation, microplastic toxicity, and bisphenol endocrine mimicry.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-sharma-05",
  },
  {
    code: "BIO-440",
    title: "CRISPR Gene Editing & Synthetic Biology",
    shortName: "CRISPR & Synthetic Bio",
    description: "Cas9, Cas12, Cas13 guide RNA targeting, base editing, prime editing, minimal synthetic bacterial genomes, and genetic biocontainment switches.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-440L",
    title: "CRISPR-Cas9 Target Cleavage & Gene Editing Lab",
    shortName: "CRISPR Lab",
    description: "In vitro sgRNA transcription, recombinant Cas9 endonuclease cleavage assay, transformation into E. coli, and blue-white colony screening.",
    subjectType: "LAB",
    courseType: "PRACTICAL",
    credits: 2,
    lectureHours: 0,
    tutorialHours: 0,
    labHours: 4,
    internalMarks: 50,
    externalMarks: 50,
    isElective: true,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-450",
    title: "Bioethics, Clinical Trials, Biosafety & IPR",
    shortName: "Bioethics & IPR",
    description: "Helsinki declaration, Institutional Biosafety Committee (IBS) protocols, GMO regulatory compliance, FDA phase I-IV trials, and gene patenting.",
    subjectType: "ABILITY_ENHANCEMENT",
    courseType: "THEORY",
    credits: 2,
    lectureHours: 2,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 50,
    externalMarks: 50,
    isElective: false,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-460",
    title: "Nanobiotechnology & Optical Biosensors",
    shortName: "Nanobiotechnology",
    description: "Surface plasmon resonance (SPR), gold nanoparticle antibody conjugates, quantum dot biolabeling, and microfluidic lab-on-a-chip diagnostics.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-470",
    title: "Pharmacogenomics & Precision Medicine",
    shortName: "Pharmacogenomics",
    description: "Single nucleotide polymorphisms (SNPs) in drug metabolism, CYP2D6/CYP2C19 polymorphisms, companion diagnostic biomarkers, and tailored chemotherapy.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 3,
    lectureHours: 3,
    tutorialHours: 0,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-480",
    title: "Single-Cell RNA Sequencing & Spatial Transcriptomics",
    shortName: "Spatial Transcriptomics",
    description: "Microfluidic single-cell partitioning (10x Genomics), UMI barcoding, Seurat dimensional reduction (UMAP/t-SNE), and tissue spatial gene mapping.",
    subjectType: "PROGRAM_ELECTIVE",
    courseType: "THEORY",
    credits: 4,
    lectureHours: 3,
    tutorialHours: 1,
    labHours: 0,
    internalMarks: 40,
    externalMarks: 60,
    isElective: true,
    facultyId: "fac-raman-02",
  },
  {
    code: "BIO-490",
    title: "Senior Capstone Thesis & Research Dissertation in Biology",
    shortName: "Biology Capstone",
    description: "Independent laboratory research investigation under faculty mentorship culminating in an ISO/peer-review standard thesis submission and public defense.",
    subjectType: "PROJECT",
    courseType: "PRACTICAL",
    credits: 6,
    lectureHours: 0,
    tutorialHours: 2,
    labHours: 8,
    internalMarks: 100,
    externalMarks: 100,
    isElective: false,
    facultyId: "fac-raman-02",
  },
];

export interface BiologyCourseConfig {
  facultyDeptBio: string;
  semBioSem1: string;
  semBioFall: string;
  semBioSem5: string;
}

export function getBiologyCoursesMaster(config: BiologyCourseConfig) {
  return BIOLOGY_COURSES.map((c) => {
    let semesterId = config.semBioFall;
    if (c.code.startsWith("BIO-1") || c.code.startsWith("MIC-1")) {
      semesterId = config.semBioSem1 || config.semBioFall;
    } else if (c.code.startsWith("BIO-4") || c.code.startsWith("MIC-4")) {
      semesterId = config.semBioSem5 || config.semBioFall;
    }

    const id = `crs-${c.code.toLowerCase().replace(/[^a-z0-9]/g, "")}`;

    return {
      id,
      code: c.code,
      title: c.title,
      shortName: c.shortName,
      description: c.description,
      departmentId: config.facultyDeptBio,
      semesterId,
      subjectType: c.subjectType,
      courseType: c.courseType,
      credits: c.credits,
      lectureHours: c.lectureHours,
      tutorialHours: c.tutorialHours,
      labHours: c.labHours,
      internalMarks: c.internalMarks,
      externalMarks: c.externalMarks,
      totalMarks: 100,
      passingMarks: c.courseType === "PRACTICAL" ? 50 : 40,
      status: "ACTIVE" as const,
      isElective: c.isElective,
      isCommon: false,
      assignedFacultyId: c.facultyId,
    };
  });
}
