import crypto from "crypto";

export interface CohortStudentSeed {
  id: string;
  userId: string;
  firstName: string;
  lastName: string;
  email: string;
  rollNumber: string;
  admissionNumber: string;
  cgpa: number;
  attendanceRate: number;
  sectionCode: string;
}

export const STUDENT_PASSWORD_PLAINTEXT = "Ilikesonpapdi115500";

export function hashCohortPassword(password: string = STUDENT_PASSWORD_PLAINTEXT): string {
  const salt = "4a8e9b1f0d3c7e5a2b6d8f0e1c3a5b7d9e1f3a5b7c9d1e3f5a7b9c1d3e5f7a9b";
  const derivedKey = crypto.pbkdf2Sync(password, salt, 100000, 64, "sha512");
  return `pbkdf2$sha512$100000$${salt}$${derivedKey.toString("hex")}`;
}

export const FULL_COHORT_STUDENTS: CohortStudentSeed[] = [
  {
    id: "stu-mercer-01",
    userId: "usr-stu-01",
    firstName: "Alex",
    lastName: "Mercer",
    email: "alex.mercer@apex.edu",
    rollNumber: "2024-CSE-042",
    admissionNumber: "ADM-2024-890",
    cgpa: 3.88,
    attendanceRate: 94.6,
    sectionCode: "5-A",
  },
  {
    id: "stu-hunt-02",
    userId: "usr-stu-02",
    firstName: "Ethan",
    lastName: "Hunt",
    email: "ethan.hunt@apex.edu",
    rollNumber: "2024-CSE-099",
    admissionNumber: "ADM-2024-911",
    cgpa: 2.95,
    attendanceRate: 64.2,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-001",
    userId: "usr-cs-001",
    firstName: "Aarav",
    lastName: "Sharma",
    email: "aarav.sharma24@gmail.com",
    rollNumber: "2024-CSE-001",
    admissionNumber: "ADM-2024-001",
    cgpa: 3.91,
    attendanceRate: 96.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-002",
    userId: "usr-cs-002",
    firstName: "Ananya",
    lastName: "Verma",
    email: "ananya.verma24@gmail.com",
    rollNumber: "2024-CSE-002",
    admissionNumber: "ADM-2024-002",
    cgpa: 3.85,
    attendanceRate: 94.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-003",
    userId: "usr-cs-003",
    firstName: "Rohan",
    lastName: "Iyer",
    email: "rohan.iyer24@gmail.com",
    rollNumber: "2024-CSE-003",
    admissionNumber: "ADM-2024-003",
    cgpa: 3.72,
    attendanceRate: 91.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-004",
    userId: "usr-cs-004",
    firstName: "Priya",
    lastName: "Patel",
    email: "priya.patel24@gmail.com",
    rollNumber: "2024-CSE-004",
    admissionNumber: "ADM-2024-004",
    cgpa: 3.96,
    attendanceRate: 98.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-005",
    userId: "usr-cs-005",
    firstName: "Kabir",
    lastName: "Singh",
    email: "kabir.singh24@gmail.com",
    rollNumber: "2024-CSE-005",
    admissionNumber: "ADM-2024-005",
    cgpa: 3.45,
    attendanceRate: 88.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-006",
    userId: "usr-cs-006",
    firstName: "Aditi",
    lastName: "Rao",
    email: "aditi.rao24@gmail.com",
    rollNumber: "2024-CSE-006",
    admissionNumber: "ADM-2024-006",
    cgpa: 3.82,
    attendanceRate: 93.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-007",
    userId: "usr-cs-007",
    firstName: "Ishan",
    lastName: "Gupta",
    email: "ishan.gupta24@gmail.com",
    rollNumber: "2024-CSE-007",
    admissionNumber: "ADM-2024-007",
    cgpa: 3.65,
    attendanceRate: 89.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-008",
    userId: "usr-cs-008",
    firstName: "Sneha",
    lastName: "Nair",
    email: "sneha.nair24@gmail.com",
    rollNumber: "2024-CSE-008",
    admissionNumber: "ADM-2024-008",
    cgpa: 3.89,
    attendanceRate: 95.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-009",
    userId: "usr-cs-009",
    firstName: "Siddharth",
    lastName: "Joshi",
    email: "siddharth.joshi24@gmail.com",
    rollNumber: "2024-CSE-009",
    admissionNumber: "ADM-2024-009",
    cgpa: 3.78,
    attendanceRate: 92.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-010",
    userId: "usr-cs-010",
    firstName: "Tanvi",
    lastName: "Kulkarni",
    email: "tanvi.kulkarni24@gmail.com",
    rollNumber: "2024-CSE-010",
    admissionNumber: "ADM-2024-010",
    cgpa: 3.94,
    attendanceRate: 97.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-011",
    userId: "usr-cs-011",
    firstName: "Vikram",
    lastName: "Mehta",
    email: "vikram.mehta24@gmail.com",
    rollNumber: "2024-CSE-011",
    admissionNumber: "ADM-2024-011",
    cgpa: 3.55,
    attendanceRate: 86.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-012",
    userId: "usr-cs-012",
    firstName: "Riya",
    lastName: "Sen",
    email: "riya.sen24@gmail.com",
    rollNumber: "2024-CSE-012",
    admissionNumber: "ADM-2024-012",
    cgpa: 3.87,
    attendanceRate: 94.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-013",
    userId: "usr-cs-013",
    firstName: "Aditya",
    lastName: "Chawla",
    email: "aditya.chawla24@gmail.com",
    rollNumber: "2024-CSE-013",
    admissionNumber: "ADM-2024-013",
    cgpa: 3.68,
    attendanceRate: 90.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-014",
    userId: "usr-cs-014",
    firstName: "Neha",
    lastName: "Reddy",
    email: "neha.reddy24@gmail.com",
    rollNumber: "2024-CSE-014",
    admissionNumber: "ADM-2024-014",
    cgpa: 3.92,
    attendanceRate: 96.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-015",
    userId: "usr-cs-015",
    firstName: "Arjun",
    lastName: "Kapoor",
    email: "arjun.kapoor24@gmail.com",
    rollNumber: "2024-CSE-015",
    admissionNumber: "ADM-2024-015",
    cgpa: 3.42,
    attendanceRate: 85.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-016",
    userId: "usr-cs-016",
    firstName: "Pooja",
    lastName: "Deshmukh",
    email: "pooja.deshmukh24@gmail.com",
    rollNumber: "2024-CSE-016",
    admissionNumber: "ADM-2024-016",
    cgpa: 3.81,
    attendanceRate: 93.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-017",
    userId: "usr-cs-017",
    firstName: "Rahul",
    lastName: "Saxena",
    email: "rahul.saxena24@gmail.com",
    rollNumber: "2024-CSE-017",
    admissionNumber: "ADM-2024-017",
    cgpa: 3.62,
    attendanceRate: 89.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-018",
    userId: "usr-cs-018",
    firstName: "Shreya",
    lastName: "Bannerjee",
    email: "shreya.bannerjee24@gmail.com",
    rollNumber: "2024-CSE-018",
    admissionNumber: "ADM-2024-018",
    cgpa: 3.95,
    attendanceRate: 97.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-019",
    userId: "usr-cs-019",
    firstName: "Varun",
    lastName: "Malhotra",
    email: "varun.malhotra24@gmail.com",
    rollNumber: "2024-CSE-019",
    admissionNumber: "ADM-2024-019",
    cgpa: 3.51,
    attendanceRate: 87.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-020",
    userId: "usr-cs-020",
    firstName: "Divya",
    lastName: "Menon",
    email: "divya.menon24@gmail.com",
    rollNumber: "2024-CSE-020",
    admissionNumber: "ADM-2024-020",
    cgpa: 3.86,
    attendanceRate: 94.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-021",
    userId: "usr-cs-021",
    firstName: "Karan",
    lastName: "Bhatia",
    email: "karan.bhatia24@gmail.com",
    rollNumber: "2024-CSE-021",
    admissionNumber: "ADM-2024-021",
    cgpa: 3.74,
    attendanceRate: 91.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-022",
    userId: "usr-cs-022",
    firstName: "Ananya",
    lastName: "Roy",
    email: "ananya.roy24@gmail.com",
    rollNumber: "2024-CSE-022",
    admissionNumber: "ADM-2024-022",
    cgpa: 3.93,
    attendanceRate: 96.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-023",
    userId: "usr-cs-023",
    firstName: "Nikhil",
    lastName: "Chopra",
    email: "nikhil.chopra24@gmail.com",
    rollNumber: "2024-CSE-023",
    admissionNumber: "ADM-2024-023",
    cgpa: 3.58,
    attendanceRate: 88.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-024",
    userId: "usr-cs-024",
    firstName: "Meera",
    lastName: "Nambiar",
    email: "meera.nambiar24@gmail.com",
    rollNumber: "2024-CSE-024",
    admissionNumber: "ADM-2024-024",
    cgpa: 3.84,
    attendanceRate: 93.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-025",
    userId: "usr-cs-025",
    firstName: "Harsh",
    lastName: "Vardhan",
    email: "harsh.vardhan24@gmail.com",
    rollNumber: "2024-CSE-025",
    admissionNumber: "ADM-2024-025",
    cgpa: 3.66,
    attendanceRate: 90.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-026",
    userId: "usr-cs-026",
    firstName: "Simran",
    lastName: "Kaur",
    email: "simran.kaur24@gmail.com",
    rollNumber: "2024-CSE-026",
    admissionNumber: "ADM-2024-026",
    cgpa: 3.90,
    attendanceRate: 95.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-027",
    userId: "usr-cs-027",
    firstName: "Devansh",
    lastName: "Trivedi",
    email: "devansh.trivedi24@gmail.com",
    rollNumber: "2024-CSE-027",
    admissionNumber: "ADM-2024-027",
    cgpa: 3.48,
    attendanceRate: 86.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-028",
    userId: "usr-cs-028",
    firstName: "Kriti",
    lastName: "Sanon",
    email: "kriti.sanon24@gmail.com",
    rollNumber: "2024-CSE-028",
    admissionNumber: "ADM-2024-028",
    cgpa: 3.88,
    attendanceRate: 94.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-029",
    userId: "usr-cs-029",
    firstName: "Ayush",
    lastName: "Mittal",
    email: "ayush.mittal24@gmail.com",
    rollNumber: "2024-CSE-029",
    admissionNumber: "ADM-2024-029",
    cgpa: 3.70,
    attendanceRate: 91.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-030",
    userId: "usr-cs-030",
    firstName: "Tara",
    lastName: "Sutaria",
    email: "tara.sutaria24@gmail.com",
    rollNumber: "2024-CSE-030",
    admissionNumber: "ADM-2024-030",
    cgpa: 3.92,
    attendanceRate: 96.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-031",
    userId: "usr-cs-031",
    firstName: "Kunal",
    lastName: "Kamra",
    email: "kunal.kamra24@gmail.com",
    rollNumber: "2024-CSE-031",
    admissionNumber: "ADM-2024-031",
    cgpa: 3.39,
    attendanceRate: 71.5, // Defaulter (< 75%)
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-032",
    userId: "usr-cs-032",
    firstName: "Disha",
    lastName: "Patani",
    email: "disha.patani24@gmail.com",
    rollNumber: "2024-CSE-032",
    admissionNumber: "ADM-2024-032",
    cgpa: 3.85,
    attendanceRate: 93.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-033",
    userId: "usr-cs-033",
    firstName: "Rishabh",
    lastName: "Pant",
    email: "rishabh.pant24@gmail.com",
    rollNumber: "2024-CSE-033",
    admissionNumber: "ADM-2024-033",
    cgpa: 3.75,
    attendanceRate: 92.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-034",
    userId: "usr-cs-034",
    firstName: "Kiara",
    lastName: "Advani",
    email: "kiara.advani24@gmail.com",
    rollNumber: "2024-CSE-034",
    admissionNumber: "ADM-2024-034",
    cgpa: 3.97,
    attendanceRate: 98.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-035",
    userId: "usr-cs-035",
    firstName: "Shubman",
    lastName: "Gill",
    email: "shubman.gill24@gmail.com",
    rollNumber: "2024-CSE-035",
    admissionNumber: "ADM-2024-035",
    cgpa: 3.80,
    attendanceRate: 93.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-036",
    userId: "usr-cs-036",
    firstName: "Smriti",
    lastName: "Mandhana",
    email: "smriti.mandhana24@gmail.com",
    rollNumber: "2024-CSE-036",
    admissionNumber: "ADM-2024-036",
    cgpa: 3.95,
    attendanceRate: 97.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-037",
    userId: "usr-cs-037",
    firstName: "Prithvi",
    lastName: "Shaw",
    email: "prithvi.shaw24@gmail.com",
    rollNumber: "2024-CSE-037",
    admissionNumber: "ADM-2024-037",
    cgpa: 3.41,
    attendanceRate: 70.0, // Defaulter (< 75%)
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-038",
    userId: "usr-cs-038",
    firstName: "Mithali",
    lastName: "Raj",
    email: "mithali.raj24@gmail.com",
    rollNumber: "2024-CSE-038",
    admissionNumber: "ADM-2024-038",
    cgpa: 3.98,
    attendanceRate: 99.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-039",
    userId: "usr-cs-039",
    firstName: "Jasprit",
    lastName: "Bumrah",
    email: "jasprit.bumrah24@gmail.com",
    rollNumber: "2024-CSE-039",
    admissionNumber: "ADM-2024-039",
    cgpa: 3.86,
    attendanceRate: 94.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-040",
    userId: "usr-cs-040",
    firstName: "Harmanpreet",
    lastName: "Kaur",
    email: "harmanpreet.kaur24@gmail.com",
    rollNumber: "2024-CSE-040",
    admissionNumber: "ADM-2024-040",
    cgpa: 3.91,
    attendanceRate: 95.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-041",
    userId: "usr-cs-041",
    firstName: "Hardik",
    lastName: "Pandya",
    email: "hardik.pandya24@gmail.com",
    rollNumber: "2024-CSE-041",
    admissionNumber: "ADM-2024-041",
    cgpa: 3.52,
    attendanceRate: 87.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-043",
    userId: "usr-cs-043",
    firstName: "Ravindra",
    lastName: "Jadeja",
    email: "ravindra.jadeja24@gmail.com",
    rollNumber: "2024-CSE-043",
    admissionNumber: "ADM-2024-043",
    cgpa: 3.89,
    attendanceRate: 95.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-044",
    userId: "usr-cs-044",
    firstName: "Deepti",
    lastName: "Sharma",
    email: "deepti.sharma24@gmail.com",
    rollNumber: "2024-CSE-044",
    admissionNumber: "ADM-2024-044",
    cgpa: 3.93,
    attendanceRate: 96.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-045",
    userId: "usr-cs-045",
    firstName: "Suryakumar",
    lastName: "Yadav",
    email: "surya.yadav24@gmail.com",
    rollNumber: "2024-CSE-045",
    admissionNumber: "ADM-2024-045",
    cgpa: 3.82,
    attendanceRate: 93.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-046",
    userId: "usr-cs-046",
    firstName: "Jemimah",
    lastName: "Rodrigues",
    email: "jemimah.rodrigues24@gmail.com",
    rollNumber: "2024-CSE-046",
    admissionNumber: "ADM-2024-046",
    cgpa: 3.94,
    attendanceRate: 97.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-047",
    userId: "usr-cs-047",
    firstName: "Mohammed",
    lastName: "Shami",
    email: "mohammed.shami24@gmail.com",
    rollNumber: "2024-CSE-047",
    admissionNumber: "ADM-2024-047",
    cgpa: 3.76,
    attendanceRate: 92.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-048",
    userId: "usr-cs-048",
    firstName: "Richa",
    lastName: "Ghosh",
    email: "richa.ghosh24@gmail.com",
    rollNumber: "2024-CSE-048",
    admissionNumber: "ADM-2024-048",
    cgpa: 3.87,
    attendanceRate: 94.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-049",
    userId: "usr-cs-049",
    firstName: "Shreyas",
    lastName: "Iyer",
    email: "shreyas.iyer24@gmail.com",
    rollNumber: "2024-CSE-049",
    admissionNumber: "ADM-2024-049",
    cgpa: 3.79,
    attendanceRate: 93.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-050",
    userId: "usr-cs-050",
    firstName: "Pooja",
    lastName: "Vastrakar",
    email: "pooja.vastrakar24@gmail.com",
    rollNumber: "2024-CSE-050",
    admissionNumber: "ADM-2024-050",
    cgpa: 3.70,
    attendanceRate: 91.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-051",
    userId: "usr-cs-051",
    firstName: "Axar",
    lastName: "Patel",
    email: "axar.patel24@gmail.com",
    rollNumber: "2024-CSE-051",
    admissionNumber: "ADM-2024-051",
    cgpa: 3.84,
    attendanceRate: 94.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-052",
    userId: "usr-cs-052",
    firstName: "Renuka",
    lastName: "Singh",
    email: "renuka.singh24@gmail.com",
    rollNumber: "2024-CSE-052",
    admissionNumber: "ADM-2024-052",
    cgpa: 3.88,
    attendanceRate: 95.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-053",
    userId: "usr-cs-053",
    firstName: "Kuldeep",
    lastName: "Yadav",
    email: "kuldeep.yadav24@gmail.com",
    rollNumber: "2024-CSE-053",
    admissionNumber: "ADM-2024-053",
    cgpa: 3.69,
    attendanceRate: 90.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-054",
    userId: "usr-cs-054",
    firstName: "Yastika",
    lastName: "Bhatia",
    email: "yastika.bhatia24@gmail.com",
    rollNumber: "2024-CSE-054",
    admissionNumber: "ADM-2024-054",
    cgpa: 3.91,
    attendanceRate: 96.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-055",
    userId: "usr-cs-055",
    firstName: "Arshdeep",
    lastName: "Singh",
    email: "arshdeep.singh24@gmail.com",
    rollNumber: "2024-CSE-055",
    admissionNumber: "ADM-2024-055",
    cgpa: 3.73,
    attendanceRate: 91.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-056",
    userId: "usr-cs-056",
    firstName: "Harleen",
    lastName: "Deol",
    email: "harleen.deol24@gmail.com",
    rollNumber: "2024-CSE-056",
    admissionNumber: "ADM-2024-056",
    cgpa: 3.85,
    attendanceRate: 94.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-057",
    userId: "usr-cs-057",
    firstName: "Mohammed",
    lastName: "Siraj",
    email: "mohammed.siraj24@gmail.com",
    rollNumber: "2024-CSE-057",
    admissionNumber: "ADM-2024-057",
    cgpa: 3.67,
    attendanceRate: 89.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-058",
    userId: "usr-cs-058",
    firstName: "Radha",
    lastName: "Yadav",
    email: "radha.yadav24@gmail.com",
    rollNumber: "2024-CSE-058",
    admissionNumber: "ADM-2024-058",
    cgpa: 3.90,
    attendanceRate: 95.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-059",
    userId: "usr-cs-059",
    firstName: "Washington",
    lastName: "Sundar",
    email: "washington.sundar24@gmail.com",
    rollNumber: "2024-CSE-059",
    admissionNumber: "ADM-2024-059",
    cgpa: 3.77,
    attendanceRate: 92.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-060",
    userId: "usr-cs-060",
    firstName: "Rajeshwari",
    lastName: "Gayakwad",
    email: "rajeshwari.gayakwad24@gmail.com",
    rollNumber: "2024-CSE-060",
    admissionNumber: "ADM-2024-060",
    cgpa: 3.86,
    attendanceRate: 94.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-061",
    userId: "usr-cs-061",
    firstName: "Tilak",
    lastName: "Varma",
    email: "tilak.varma24@gmail.com",
    rollNumber: "2024-CSE-061",
    admissionNumber: "ADM-2024-061",
    cgpa: 3.78,
    attendanceRate: 93.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-062",
    userId: "usr-cs-062",
    firstName: "Amanjot",
    lastName: "Kaur",
    email: "amanjot.kaur24@gmail.com",
    rollNumber: "2024-CSE-062",
    admissionNumber: "ADM-2024-062",
    cgpa: 3.89,
    attendanceRate: 95.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-063",
    userId: "usr-cs-063",
    firstName: "Rinku",
    lastName: "Singh",
    email: "rinku.singh24@gmail.com",
    rollNumber: "2024-CSE-063",
    admissionNumber: "ADM-2024-063",
    cgpa: 3.81,
    attendanceRate: 93.5,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-064",
    userId: "usr-cs-064",
    firstName: "Sushma",
    lastName: "Verma",
    email: "sushma.verma24@gmail.com",
    rollNumber: "2024-CSE-064",
    admissionNumber: "ADM-2024-064",
    cgpa: 3.92,
    attendanceRate: 96.0,
    sectionCode: "5-A",
  },
  {
    id: "stu-cs-065",
    userId: "usr-cs-065",
    firstName: "Yashasvi",
    lastName: "Jaiswal",
    email: "yashasvi.jaiswal24@gmail.com",
    rollNumber: "2024-CSE-065",
    admissionNumber: "ADM-2024-065",
    cgpa: 3.95,
    attendanceRate: 97.5,
    sectionCode: "5-A",
  },
];

/**
 * Inserts or updates all 65 students in the database with password Ilikesonpapdi115500
 * and enrolls them into Section 5-A and relevant Semester 5 courses.
 */
export async function seedCohortStudents(prisma: any, institutionId: string, progCsId: string, secCs5A: string) {
  const passwordHash = hashCohortPassword();
  const targetCourses = ["CS-402", "CS-402L", "CS-301", "CS-480"];

  const resolvedCourses: any[] = [];
  for (const cCode of targetCourses) {
    const c = await prisma.course.findFirst({ where: { code: cCode } });
    if (c) resolvedCourses.push(c);
  }

  for (const item of FULL_COHORT_STUDENTS) {
    // 1. Create or update User
    let user = await prisma.user.findUnique({ where: { email: item.email } });
    if (!user) {
      user = await prisma.user.create({
        data: {
          id: item.userId,
          institutionId,
          email: item.email,
          passwordHash,
          firstName: item.firstName,
          lastName: item.lastName,
          role: "STUDENT",
          isActive: true,
          mustChangePassword: false,
        },
      });
    } else {
      // Ensure password is updated to Ilikesonpapdi115500
      await prisma.user.update({
        where: { id: user.id },
        data: { passwordHash, isActive: true },
      });
    }

    // 2. Create or update Student profile
    let student = await prisma.student.findUnique({ where: { userId: user.id } });
    if (!student) {
      student = await prisma.student.create({
        data: {
          id: item.id,
          userId: user.id,
          programId: progCsId,
          sectionId: secCs5A,
          rollNumber: item.rollNumber,
          admissionNumber: item.admissionNumber,
          admissionDate: new Date("2024-08-01"),
          currentSemester: 5,
          cgpa: item.cgpa,
          attendanceRate: item.attendanceRate,
          status: "ACTIVE",
        },
      });
    } else {
      await prisma.student.update({
        where: { id: student.id },
        data: {
          sectionId: secCs5A,
          programId: progCsId,
          currentSemester: 5,
          rollNumber: item.rollNumber,
          attendanceRate: item.attendanceRate,
        },
      });
    }

    // 3. Enroll student into CS-402 and other courses
    for (const crs of resolvedCourses) {
      await prisma.enrollment.upsert({
        where: {
          studentId_courseId: {
            studentId: student.id,
            courseId: crs.id,
          },
        },
        update: { status: "ENROLLED" },
        create: {
          studentId: student.id,
          courseId: crs.id,
          status: "ENROLLED",
        },
      }).catch(() => {});
    }
  }

  return FULL_COHORT_STUDENTS.length;
}
